### ISSUE TITLE
White screen on Unity project after initiating magic.Auth.LoginWithMagicLink

### ISSUE THREAD

**Issue by irfan-acxyn** [magiclabs/magic-unity#10]
**App API** pk_live_9A51173BEDC0AF7A
**Magic Publishable** API pk_live_BD2FA7734BCD98C3

We have tried two functions alternatively but same issue with both. The functions are:

1. magic.Auth.LoginWithMagicLink("pilaxin924@soombo.com")
2. magic.Auth.LoginWithEmailOtp("pilaxin924@soombo.com")

The webview UI hasn’t appeared since the beginning, not even once. Also, we haven’t explicitly suppressed any webview UI.

**Comment by am-hernandez** [comment]
Hello @irfan-acxyn ,

Would you please provide a code snippet of how you are handling the login logic? 
You may also follow the [Quickstart](https://github.com/magiclabs/magic-unity#quick-start) in the README, if you haven't already.

**Comment by captainIN** [comment]
Hey @am-hernandez ,

Here is the code snippet for Login Flow.

```csharp
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using link.magic.unity.sdk;
public class LoginFlow : MonoBehaviour
{
    void Start()
    {
        Magic magic = new Magic("pk_live_9A51173BEDC0AF7A");
        
        // Append the instance here, so that it can be shared across the project
        Magic.Instance = magic;
    }

     public async void Login()
    {
        Magic magic = Magic.Instance;
        var token = await magic.Auth.LoginWithMagicLink("vixabo7204@appxapi.com");
        Debug.Log("token ="+token);
    }
}
```

Below are the screenshots of the issue.
<img width="1299" alt="Screenshot 2023-05-16 at 11 27 00 AM" src="https://github.com/magiclabs/magic-unity/assets/46473602/224236f5-3e7f-4927-b3a3-d99965029444">
<img width="1270" alt="Screenshot 2023-05-16 at 11 27 41 AM" src="https://github.com/magiclabs/magic-unity/assets/46473602/b149663a-d794-46d1-a033-346c7c03a03a">

**Comment by irfan-acxyn** [comment]
Thanks for supporting us on this ticket, @am-hernandez – **captainIN (** _Jaymanyoo_ **)** is supporting my team on the app's development.

Let us know if there's anything further we can help to clarify! Any cap from your team's end would be hugely appreciated, as this issue's been pending a little over two weeks now, and it's painfully urgent.

**Comment by ayv8er** [comment]
Thank you for notifying us about this matter. We've added it to our task queue and will be working diligently to address it. However, given our current resource constraints, we won't be able to effectively resolve this issue in the short term. We appreciate your understanding and patience as we navigate through our workload.

**Comment by irfan-acxyn** [comment]
_We appreciate the visibility on your constraints @ayv8er @am-hernandez ._

**Could we trouble your team to overestimate when this issue can be revisited?** 
Just approximate the week/month, and this would significantly help to advise our product's roadmap, as this feature's been a showstopper for the past three weeks.

**Comment by ayv8er** [comment]
@irfan-acxyn 
Our team will investigate this next week, and I will provide an update by the end of next week.

**Comment by irfan-acxyn** [comment]
@ayv8er 
We appreciate your team's time spent investigating this, it'd really help us in continuing to work with Magic's solutions.

Looking forward to hearing from you, Richard!

**Comment by ayv8er** [comment]
@irfan-acxyn 
Our team had to deal with some urgent issues this week.
Please let me follow up after reprioritization to see when we could look into this.

**Comment by irfan-acxyn** [comment]
@ayv8er @am-hernandez 
Hey team, how's reprioritisation looking like so far? It's coming to 1.5 months since we've tried to resolve this.

cc: @Ethella

**Comment by Ariflo** [comment]
@irfan-acxyn This is still on our docket and will be addressed within the next few days. Our sincerest apologies for the delay!

**Comment by irfan-acxyn** [comment]
Thanks for creating some visibility @Ariflo ! 

Let me know if it isn't possible to check-in with your team before the weekends regarding this, happy to help in any way.

**Comment by irfan-acxyn** [comment]
Hey @Ariflo , checking-in with your team before it hits the weekends for us here in Singapore – can I ask if you were able to briefly look at the issue, and advise how we might move forward? Cheers!

**Comment by Ariflo** [comment]
@irfan-acxyn we are still digging into it on our end, can you confirm whether or not you see the same issue crop up when using or demo app [Magic Example.prefab](https://github.com/magiclabs/magic-unity/tree/main/link.magic.unity.sdk/Prefabs)?

**Comment by irfan-acxyn** [comment]
Unfortunately, even with the demo app, the same debug logs crop up. 
<img width="1017" alt="Screenshot 2023-06-09 at 3 38 10 PM" src="https://github.com/magiclabs/magic-unity/assets/132328788/838faac3-4572-4c77-8b51-c2eca18f8f5f">

Appreciate you & your team's time on this, @Ariflo.

**Comment by Ariflo** [comment]
@irfan-acxyn still debugging here. Will keep you posted on here when the fix its up

**Comment by JackShiu** [comment]
Hi all, I'm facing the same issue as well.

**Comment by irfan-acxyn** [comment]
Sorry to hear that @JackShiu – any workarounds on your end? Or are you still having this blocker? My team's tried to have this resolve since late-April. We'd suggest you to checkout Web3Auth as a temporary hack.

Cheers!

**Comment by Ariflo** [comment]
@JackShiu @irfan-acxyn Apologies again for the delay. We've been doing our best to reproduce your error to no avail. As of today, we were able to get the Webview to appear inside of a simple 2D Unity project with our demo app:

## Android Simulator

![2023-07-06 16 53 38](https://github.com/magiclabs/magic-unity/assets/13407884/304219a0-a04d-476a-91da-625dc8f5e473)

![2023-07-06 16 52 04](https://github.com/magiclabs/magic-unity/assets/13407884/82019ef9-d70e-421b-9ee2-92c157f44413)



Let us know if there's anything more we should be doing to mimic your setups. Thanks!

**Comment by am-hernandez** [comment]
@JackShiu @irfan-acxyn 

Just circling back to see if you have any additional context to share on this issue? If not we will close this issue and you may open a new issue if the problem persists.

**Comment by ayv8er** [comment]
@JackShiu @irfan-acxyn
We'll be closing this issue as we cannot continue assisting you.
We will be more than happy to re-open if you can provide some feedback.
