### ISSUE TITLE
Register device to continue additional security check 

### ISSUE THREAD

**Issue by basitcubix** [magiclabs/magic-unity#12]
hey I was using email Otp for my authentication and i don't want to open your web browser we were handling it with our own UI it was working fine till yesterday but now I am getting "register device to continue" Why this check is included is there any way to remove it because i don't want my user to have multiple security checks.

**Comment by am-hernandez** [comment]
@basitcubix , this can be removed. Would you please contact our support via the widget in the bottom-right corner of our homepage on https://magic.link/ ?

Thank you!
