### ISSUE TITLE
included Common dlls conflicting with existing packages

### ISSUE THREAD

**Issue by CineTek** [magiclabs/magic-unity#7]
After importing the latest release into our Unity project we receive compilation errors coming from the official Unity Collections package that is used by various other components in the project.

Library\PackageCache\com.unity.collections@1.2.4\Unity.Collections\xxHash3.cs(465,27): error CS0234: The type or namespace name 'umul128' does not exist in the namespace 'Common' (are you missing an assembly reference?)

Apparently there is a conflict between the included Nethereum version which has a custom Commons.dll in the Magic package.

The same underlying issue can be found here but the proposed solution (hack) is impossible for us to implement. 
https://github.com/MoralisWeb3/unity-web3-game-kit/issues/76

A solution could be to update this Magic package to the latest Nethereum SDK but this only brings up additional errors and unintended behavior if done locally on our end.

**Comment by Ethella** [comment]
Please feel free to try out the latest version 3.1, which now includes Unity Package Manager (UPM) for dependency management. With this, I'm closing the issue.
