### ISSUE TITLE
Cant get response from server(Its working in IOS)

### ISSUE THREAD

**Issue by basitcubix** [magiclabs/magic-unity#9]
i cant get to  authenticate to my magic email because i cant get response from the server on my unity project. Its working fine if i change the bundle id or change the platform to IOS. its not working on Android

**Comment by ayv8er** [comment]
@basitcubix would you be able to provide more information on this? 
If working fine for iOS but not for Android, what is the bundle id you're passing?
If you'd like to avoid posting this publicly, please reach out to us via chat box on our home page https://magic.link/

**Comment by basitcubix** [comment]
com.wagmigame
